config/routes.rb
Rails.application.routes.draw do
  resources :subjects
  # resources :skillsets
  root  'skillsets#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'skillsets/new' => 'skillsets#new'

  # post 'skillsets/create' => 'skillsets#create'
  resources :skillsets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/skillset.rb
class Skillset < ApplicationRecord
  belongs_to :subject

end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :skillsets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/skillsets_controller.rb
class SkillsetsController < ApplicationController
  before_action :set_skillset, only: [:show, :edit, :update, :destroy]

  # GET /skillsets
  # GET /skillsets.json
  def index
    @skillsets = Skillset.all
  end

  # GET /skillsets/1
  # GET /skillsets/1.json
  def show
  end

  # GET /skillsets/new
  def new
    @skillset =  Skillset.new
  end

  # GET /skillsets/1/edit
  def edit
  end

  def destroy
  end
  # POST /skillsets
  # POST /skillsets.json
  def create
    @skillset = Skillset.new(skillset_params)

    respond_to do |format|
      if @skillset.save
        format.html { redirect_to @skillset, notice: 'Skillset was successfully created.' }
        format.json { render :show, status: :created, location: @skillset }
      else
        format.html { render :new }
        format.json { render json: @skillset.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /skillsets/1
  # PATCH/PUT /skillsets/1.json
  def update
    respond_to do |format|
      if @skillset.update(skillset_params)
        format.html { redirect_to @skillset, notice: 'Skillset was successfully updated.' }
        format.json { render :show, status: :ok, location: @skillset }
      else
        format.html { render :edit }
        format.json { render json: @skillset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skillsets/1
  # DELETE /skillsets/1.json
  def destroy
    @skillset.destroy
    respond_to do |format|
      format.html { redirect_to skillsets_url, notice: 'Skillset was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_skillset
      @skillset = Skillset.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def skillset_params
      params.require(:skillset).permit(:skill, :hours_studied, :code, :subject_id)
    end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/skillsets_helper.rb
module SkillsetsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>CodesSkillsTracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Lato:700,400" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/skillsets/_form.html.erb
<%= form_with(model: skillset, local: true) do |form| %>


  <div class="field">
    <%= form.label :skill %>
    <%= form.text_field :skill %>
  </div>

  <div class="field">
    <%= form.label :hours_studied %>
    <%= form.number_field :hours_studied%>
  </div>

  <div class="field">
    <%= form.label :code %>
    <%= form.check_box :code %>
  </div>

  <div class="field">
    <%= form.label :subject_id %>
    <%= form.text_field :subject_id %>
  </div>

  <div class="actions">
    <%= form.submit "Enter" %>
  </div>
<% end %>

app/views/skillsets/edit.html.erb
<h1>Editing Skillset</h1>

<%= render 'form', skillset: @skillset %>

<%= link_to 'Show', @skillset %> |
<%= link_to 'Back', skillsets_path %>

app/views/skillsets/index.html.erb
<div class="container-body">
    <% @skillsets.each do |skillset| %>





    <br>

    <h3> SUBJECT <span><%= skillset.skill %></span></h3>

    <ul>
       <li><b><%= skillset.subject.name %></b></li>
        <li><b><%= skillset.hours_studied %></b>Hours studied</li>
        <li><b><%= link_to 'Show', skillset %></li>
        <li><b><%= link_to 'Edit', edit_skillset_path(skillset) %></li>
  <li><b><%= link_to 'Destroy', skillset, method: :delete, data: { confirm: 'Are you sure?' } %></li>
    <li><b>Proficient?  </b><%= skillset.code %></li>
    </ul>

    <% end %>

    <br>

    <%= link_to 'Add a new skill', new_skillset_path %>
</table>

<br>

</div>

<div id="pricing-table" class="clear">
    <div class="plan">
        <h3>RUBY<span>skill</span></h3>
        <a class="signup" href="">Sign up</a>
        <ul>
            <li><b>10GB</b> Disk Space</li>
            <li><b>100GB</b> Monthly Bandwidth</li>
            <li><b>20</b> Email Accounts</li>
			<li><b>Unlimited</b> subdomains</li>
        </ul>
    </div>
    <div class="plan" id="most-popular">
        <h3>Professional<span>$29</span></h3>
        <a class="signup" href="">Sign up</a>
        <ul>
            <li><b>5GB</b> Disk Space</li>
            <li><b>50GB</b> Monthly Bandwidth</li>
            <li><b>10</b> Email Accounts</li>
			<li><b>Unlimited</b> subdomains</li>
        </ul>
    </div>
    <div class="plan">
        <h3>Standard<span>$17</span></h3>
		<a class="signup" href="">Sign up</a>
        <ul>
            <li><b>3GB</b> Disk Space</li>
            <li><b>25GB</b> Monthly Bandwidth</li>
            <li><b>5</b> Email Accounts</li>
			<li><b>Unlimited</b> subdomains</li>
        </ul>
    </div>
    <div class="plan">
        <h3>Basic<span>$9</span></h3>
        <a class="signup" href="">Sign up</a>
        <ul>
            <li><b>1GB</b> Disk Space</li>
            <li><b>10GB</b> Monthly Bandwidth</li>
            <li><b>2</b> Email Accounts</li>
			<li><b>Unlimited</b> subdomains</li>
        </ul>
    </div>
</div>

app/views/skillsets/new.html.erb
<h1>New Skillset</h1>

<%=render 'form', skillset: @skillset %>

<%# link_to 'Back', skillsets_path %>

app/views/skillsets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Skill:</strong>
  <%= @skillset.skill %>
</p>

<p>
  <strong>Hours studied:</strong>
  <%= @skillset.hours_studied %>
</p>

<p>
  <strong>Code:</strong>
  <%= @skillset.code %>
</p>

<%= link_to 'Edit', edit_skillset_path(@skillset) %> |
<%= link_to 'Back', skillsets_path %>

app/views/subjects/_form.html.erb
<%= form_with(model: subject, local: true) do |form| %>
  <% if subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% subject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :subject_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :subject_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<h1>Editing Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subjects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.name %></td>
        <td><%= subject.description %></td>
        <td><%= link_to 'Show', subject %></td>
        <td><%= link_to 'Edit', edit_subject_path(subject) %></td>
        <td><%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subject', new_subject_path %>

app/views/subjects/new.html.erb
<h1>New Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Back', subjects_path %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @subject.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @subject.description %>
</p>

<%= link_to 'Edit', edit_subject_path(@subject) %> |
<%= link_to 'Back', subjects_path %>